[2024-05-06 14:40:59.279][  INFO   ]|     logger.py      |MOD:       logger       |FUNC:      <module>      |Line:145 [LOG] test
[2024-05-06 14:40:59.396][  INFO   ]|    read_yaml.py    |MOD:     read_yaml      |FUNC:     read_yaml      |Line: 16 [LOG] ./config/config.yaml配置字读取成功,读到的内容为{'prject': 'a8e', 'devices': '192.168.7.16:5555', 'qnx_ip': '192.168.118.2', 'qnx_user': 'root', 'qnx_passwd': '', 'qnx_screenshot_path': '/var/share/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'adb_pull_dest': './test/output_images/', 'android_log_path': '/mnt/user/log_android/', 'qnx_log_path': '/data/nfs/nfs_log/', 'cfg_path': './common/can/canoe_project/Configuration.cfg', 'dbc_path': './common/can/canoe_project/A8E_Proj_IHU_PFET_CMX+V1.25_20230421.dbc', 'video_path': 'E:/工作文档/学习文档/自动化/cluster_autotest/testdata', 'camera_index': 0, 'video_fps': 25}
[2024-05-06 14:40:59.421][  INFO   ]|    read_yaml.py    |MOD:     read_yaml      |FUNC:     read_yaml      |Line: 16 [LOG] ./config/config.yaml配置字读取成功,读到的内容为{'prject': 'a8e', 'devices': '192.168.7.16:5555', 'qnx_ip': '192.168.118.2', 'qnx_user': 'root', 'qnx_passwd': '', 'qnx_screenshot_path': '/var/share/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'adb_pull_dest': './test/output_images/', 'android_log_path': '/mnt/user/log_android/', 'qnx_log_path': '/data/nfs/nfs_log/', 'cfg_path': './common/can/canoe_project/Configuration.cfg', 'dbc_path': './common/can/canoe_project/A8E_Proj_IHU_PFET_CMX+V1.25_20230421.dbc', 'video_path': 'E:/工作文档/学习文档/自动化/cluster_autotest/testdata', 'camera_index': 0, 'video_fps': 25}
[2024-05-06 14:41:08.842][  INFO   ]|      canoe.py      |MOD:       canoe        |FUNC:      __init__      |Line: 21 [LOG] Loaded CANoe version 
[2024-05-06 14:41:08.846][  INFO   ]|      canoe.py      |MOD:       canoe        |FUNC:      __init__      |Line: 26 [LOG] CANoe初始化成功
[2024-05-06 14:41:11.247][ WARNING ]|      canoe.py      |MOD:       canoe        |FUNC:      open_cfg      |Line: 42 [LOG] opening..../common/can/canoe_project/Configuration.cfg
[2024-05-06 14:41:16.325][  ERROR  ]|      canoe.py      |MOD:       canoe        |FUNC: start_Measurement  |Line: 81 [LOG] CANoe启动测量失败,请检查连接
[2024-05-06 14:41:16.326][  ERROR  ]|      canoe.py      |MOD:       canoe        |FUNC: start_Measurement  |Line: 85 [LOG] CANoe start measuremet failed, Please Check Connection!
